# 相关内容配置
includeNewer = true  # 是否包含较新的内容
threshold = 60       # 相关性阈值
toLower = false      # 是否转换为小写

[[indices]]
name = "Tag"   # 索引名称
weight = 100     # 权重

[[indices]]
name = "分类"  # 索引名称
weight = 200          # 权重
